# Generated by Django 5.2.9 on 2025-12-04 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_stock_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='quantity',
            new_name='quantity_sold',
        ),
        migrations.RenameField(
            model_name='salesrecord',
            old_name='date',
            new_name='sale_date',
        ),
    ]
